[package]
name = "rustshop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { version = "0.6.1" }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rustshop-env = { version = "*", path = "../env/" }
clap = { version = "3.1.6", features = [ "derive", "env" ] }
clap_complete = "3.2.3"
error-stack = "0.1.1"
derive_more = "0.99.17"
serde = "1.0.138"
serde_json = "1.0.82"
tempfile = "3.3.0"
